/* tslint:disable */
/* eslint-disable */
/**
 * QuantU Services API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ErrorResponse model
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
	/**
	 *
	 * @type {Array<string>}
	 * @memberof ErrorResponse
	 */
	errors: Array<string>;
}

/**
 * Check if a given object implements the ErrorResponse interface.
 */
export function instanceOfErrorResponse(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'errors' in value;

	return isInstance;
}

export function ErrorResponseFromJSON(json: any): ErrorResponse {
	return ErrorResponseFromJSONTyped(json, false);
}

export function ErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponse {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		errors: json['errors']
	};
}

export function ErrorResponseToJSON(value?: ErrorResponse | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		errors: value.errors
	};
}
