/* tslint:disable */
/* eslint-disable */
/**
 * QuantU Services API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Mercury_Entities_Token model
 * @export
 * @interface MercuryEntitiesToken
 */
export interface MercuryEntitiesToken {
    /**
     * 
     * @type {string}
     * @memberof MercuryEntitiesToken
     */
    token: string;
    /**
     * 
     * @type {number}
     * @memberof MercuryEntitiesToken
     */
    exp: number;
}

/**
 * Check if a given object implements the MercuryEntitiesToken interface.
 */
export function instanceOfMercuryEntitiesToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "exp" in value;

    return isInstance;
}

export function MercuryEntitiesTokenFromJSON(json: any): MercuryEntitiesToken {
    return MercuryEntitiesTokenFromJSONTyped(json, false);
}

export function MercuryEntitiesTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): MercuryEntitiesToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'exp': json['exp'],
    };
}

export function MercuryEntitiesTokenToJSON(value?: MercuryEntitiesToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'exp': value.exp,
    };
}

