/* tslint:disable */
/* eslint-disable */
/**
 * QuantU Services API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Mercury_Entities_ErrorResponse model
 * @export
 * @interface MercuryEntitiesErrorResponse
 */
export interface MercuryEntitiesErrorResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof MercuryEntitiesErrorResponse
     */
    errors: Array<string>;
}

/**
 * Check if a given object implements the MercuryEntitiesErrorResponse interface.
 */
export function instanceOfMercuryEntitiesErrorResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "errors" in value;

    return isInstance;
}

export function MercuryEntitiesErrorResponseFromJSON(json: any): MercuryEntitiesErrorResponse {
    return MercuryEntitiesErrorResponseFromJSONTyped(json, false);
}

export function MercuryEntitiesErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MercuryEntitiesErrorResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': json['errors'],
    };
}

export function MercuryEntitiesErrorResponseToJSON(value?: MercuryEntitiesErrorResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': value.errors,
    };
}

