/* tslint:disable */
/* eslint-disable */
/**
 * QuantU Services API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Mercury_Entities_Quiz model
 * @export
 * @interface MercuryEntitiesQuiz
 */
export interface MercuryEntitiesQuiz {
    /**
     * 
     * @type {number}
     * @memberof MercuryEntitiesQuiz
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MercuryEntitiesQuiz
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MercuryEntitiesQuiz
     */
    uri: string;
    /**
     * 
     * @type {Date}
     * @memberof MercuryEntitiesQuiz
     */
    created_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof MercuryEntitiesQuiz
     */
    updated_at: Date;
}

/**
 * Check if a given object implements the MercuryEntitiesQuiz interface.
 */
export function instanceOfMercuryEntitiesQuiz(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "uri" in value;
    isInstance = isInstance && "created_at" in value;
    isInstance = isInstance && "updated_at" in value;

    return isInstance;
}

export function MercuryEntitiesQuizFromJSON(json: any): MercuryEntitiesQuiz {
    return MercuryEntitiesQuizFromJSONTyped(json, false);
}

export function MercuryEntitiesQuizFromJSONTyped(json: any, ignoreDiscriminator: boolean): MercuryEntitiesQuiz {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'uri': json['uri'],
        'created_at': (new Date(json['created_at'])),
        'updated_at': (new Date(json['updated_at'])),
    };
}

export function MercuryEntitiesQuizToJSON(value?: MercuryEntitiesQuiz | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'uri': value.uri,
        'created_at': (value.created_at.toISOString()),
        'updated_at': (value.updated_at.toISOString()),
    };
}

