/* tslint:disable */
/* eslint-disable */
/**
 * QuantU Services API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Update a Question
 * @export
 * @interface PatchApiQuizzesQuizIdQuestionsId
 */
export interface PatchApiQuizzesQuizIdQuestionsId {
    /**
     * 
     * @type {string}
     * @memberof PatchApiQuizzesQuizIdQuestionsId
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchApiQuizzesQuizIdQuestionsId
     */
    item_order_position?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchApiQuizzesQuizIdQuestionsId
     */
    question_type?: PatchApiQuizzesQuizIdQuestionsIdQuestionTypeEnum;
}


/**
 * @export
 */
export const PatchApiQuizzesQuizIdQuestionsIdQuestionTypeEnum = {
    FlashCard: 'flash_card'
} as const;
export type PatchApiQuizzesQuizIdQuestionsIdQuestionTypeEnum = typeof PatchApiQuizzesQuizIdQuestionsIdQuestionTypeEnum[keyof typeof PatchApiQuizzesQuizIdQuestionsIdQuestionTypeEnum];


/**
 * Check if a given object implements the PatchApiQuizzesQuizIdQuestionsId interface.
 */
export function instanceOfPatchApiQuizzesQuizIdQuestionsId(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchApiQuizzesQuizIdQuestionsIdFromJSON(json: any): PatchApiQuizzesQuizIdQuestionsId {
    return PatchApiQuizzesQuizIdQuestionsIdFromJSONTyped(json, false);
}

export function PatchApiQuizzesQuizIdQuestionsIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchApiQuizzesQuizIdQuestionsId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'item_order_position': !exists(json, 'item_order_position') ? undefined : json['item_order_position'],
        'question_type': !exists(json, 'question_type') ? undefined : json['question_type'],
    };
}

export function PatchApiQuizzesQuizIdQuestionsIdToJSON(value?: PatchApiQuizzesQuizIdQuestionsId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'item_order_position': value.item_order_position,
        'question_type': value.question_type,
    };
}

