/* tslint:disable */
/* eslint-disable */
/**
 * QuantU Services API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Update a quiz
 * @export
 * @interface PatchApiQuizzesId
 */
export interface PatchApiQuizzesId {
	/**
	 * Name
	 * @type {string}
	 * @memberof PatchApiQuizzesId
	 */
	name?: string;
}

/**
 * Check if a given object implements the PatchApiQuizzesId interface.
 */
export function instanceOfPatchApiQuizzesId(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function PatchApiQuizzesIdFromJSON(json: any): PatchApiQuizzesId {
	return PatchApiQuizzesIdFromJSONTyped(json, false);
}

export function PatchApiQuizzesIdFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): PatchApiQuizzesId {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		name: !exists(json, 'name') ? undefined : json['name']
	};
}

export function PatchApiQuizzesIdToJSON(value?: PatchApiQuizzesId | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		name: value.name
	};
}
