/* tslint:disable */
/* eslint-disable */
/**
 * QuantU Services API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Update a Study Session
 * @export
 * @interface PatchApiStudySessionsId
 */
export interface PatchApiStudySessionsId {
	/**
	 *
	 * @type {object}
	 * @memberof PatchApiStudySessionsId
	 */
	data?: object;
}

/**
 * Check if a given object implements the PatchApiStudySessionsId interface.
 */
export function instanceOfPatchApiStudySessionsId(value: object): boolean {
	let isInstance = true;

	return isInstance;
}

export function PatchApiStudySessionsIdFromJSON(json: any): PatchApiStudySessionsId {
	return PatchApiStudySessionsIdFromJSONTyped(json, false);
}

export function PatchApiStudySessionsIdFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): PatchApiStudySessionsId {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		data: !exists(json, 'data') ? undefined : json['data']
	};
}

export function PatchApiStudySessionsIdToJSON(value?: PatchApiStudySessionsId | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		data: value.data
	};
}
