/* tslint:disable */
/* eslint-disable */
/**
 * QuantU Services API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Move a Question to a new position within the ordered questions list
 * @export
 * @interface PatchApiQuizzesQuizIdQuestionsIdMove
 */
export interface PatchApiQuizzesQuizIdQuestionsIdMove {
    /**
     * 
     * @type {number}
     * @memberof PatchApiQuizzesQuizIdQuestionsIdMove
     */
    item_order_position: number;
}

/**
 * Check if a given object implements the PatchApiQuizzesQuizIdQuestionsIdMove interface.
 */
export function instanceOfPatchApiQuizzesQuizIdQuestionsIdMove(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "item_order_position" in value;

    return isInstance;
}

export function PatchApiQuizzesQuizIdQuestionsIdMoveFromJSON(json: any): PatchApiQuizzesQuizIdQuestionsIdMove {
    return PatchApiQuizzesQuizIdQuestionsIdMoveFromJSONTyped(json, false);
}

export function PatchApiQuizzesQuizIdQuestionsIdMoveFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchApiQuizzesQuizIdQuestionsIdMove {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'item_order_position': json['item_order_position'],
    };
}

export function PatchApiQuizzesQuizIdQuestionsIdMoveToJSON(value?: PatchApiQuizzesQuizIdQuestionsIdMove | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item_order_position': value.item_order_position,
    };
}

