/* tslint:disable */
/* eslint-disable */
/**
 * QuantU Services API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Create a new question
 * @export
 * @interface PostApiQuestions
 */
export interface PostApiQuestions {
	/**
	 *
	 * @type {string}
	 * @memberof PostApiQuestions
	 */
	name?: string;
	/**
	 *
	 * @type {number}
	 * @memberof PostApiQuestions
	 */
	item_order_position?: number;
	/**
	 *
	 * @type {object}
	 * @memberof PostApiQuestions
	 */
	data: object;
	/**
	 *
	 * @type {string}
	 * @memberof PostApiQuestions
	 */
	question_type: PostApiQuestionsQuestionTypeEnum;
}

/**
 * @export
 */
export const PostApiQuestionsQuestionTypeEnum = {
	FlashCard: 'flash_card'
} as const;
export type PostApiQuestionsQuestionTypeEnum =
	(typeof PostApiQuestionsQuestionTypeEnum)[keyof typeof PostApiQuestionsQuestionTypeEnum];

/**
 * Check if a given object implements the PostApiQuestions interface.
 */
export function instanceOfPostApiQuestions(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'data' in value;
	isInstance = isInstance && 'question_type' in value;

	return isInstance;
}

export function PostApiQuestionsFromJSON(json: any): PostApiQuestions {
	return PostApiQuestionsFromJSONTyped(json, false);
}

export function PostApiQuestionsFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): PostApiQuestions {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		name: !exists(json, 'name') ? undefined : json['name'],
		item_order_position: !exists(json, 'item_order_position')
			? undefined
			: json['item_order_position'],
		data: json['data'],
		question_type: json['question_type']
	};
}

export function PostApiQuestionsToJSON(value?: PostApiQuestions | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		name: value.name,
		item_order_position: value.item_order_position,
		data: value.data,
		question_type: value.question_type
	};
}
