/* tslint:disable */
/* eslint-disable */
/**
 * QuantU Services API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Login and return a new JWT access token
 * @export
 * @interface PostApiAuthLogin
 */
export interface PostApiAuthLogin {
	/**
	 * User email
	 * @type {string}
	 * @memberof PostApiAuthLogin
	 */
	email: string;
	/**
	 * User Password
	 * @type {string}
	 * @memberof PostApiAuthLogin
	 */
	password: string;
}

/**
 * Check if a given object implements the PostApiAuthLogin interface.
 */
export function instanceOfPostApiAuthLogin(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && 'email' in value;
	isInstance = isInstance && 'password' in value;

	return isInstance;
}

export function PostApiAuthLoginFromJSON(json: any): PostApiAuthLogin {
	return PostApiAuthLoginFromJSONTyped(json, false);
}

export function PostApiAuthLoginFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): PostApiAuthLogin {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		email: json['email'],
		password: json['password']
	};
}

export function PostApiAuthLoginToJSON(value?: PostApiAuthLogin | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		email: value.email,
		password: value.password
	};
}
