/* tslint:disable */
/* eslint-disable */
/**
 * QuantU Services API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Create a new question result
 * @export
 * @interface PostApiQuestionResults
 */
export interface PostApiQuestionResults {
    /**
     * Question ID
     * @type {number}
     * @memberof PostApiQuestionResults
     */
    question_id: number;
    /**
     * Learning Session ID
     * @type {number}
     * @memberof PostApiQuestionResults
     */
    study_session_id?: number;
    /**
     * 
     * @type {object}
     * @memberof PostApiQuestionResults
     */
    data: object;
}

/**
 * Check if a given object implements the PostApiQuestionResults interface.
 */
export function instanceOfPostApiQuestionResults(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "question_id" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function PostApiQuestionResultsFromJSON(json: any): PostApiQuestionResults {
    return PostApiQuestionResultsFromJSONTyped(json, false);
}

export function PostApiQuestionResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiQuestionResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'question_id': json['question_id'],
        'study_session_id': !exists(json, 'study_session_id') ? undefined : json['study_session_id'],
        'data': json['data'],
    };
}

export function PostApiQuestionResultsToJSON(value?: PostApiQuestionResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'question_id': value.question_id,
        'study_session_id': value.study_session_id,
        'data': value.data,
    };
}

