/* tslint:disable */
/* eslint-disable */
/**
 * QuantU Services API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MercuryEntitiesErrorResponse,
  MercuryEntitiesToken,
  MercuryEntitiesUser,
  PostApiAuthLogin,
} from '../models';
import {
    MercuryEntitiesErrorResponseFromJSON,
    MercuryEntitiesErrorResponseToJSON,
    MercuryEntitiesTokenFromJSON,
    MercuryEntitiesTokenToJSON,
    MercuryEntitiesUserFromJSON,
    MercuryEntitiesUserToJSON,
    PostApiAuthLoginFromJSON,
    PostApiAuthLoginToJSON,
} from '../models';

export interface PostApiAuthLoginRequest {
    postApiAuthLogin: PostApiAuthLogin;
}

/**
 * AuthApi - interface
 * 
 * @export
 * @interface AuthApiInterface
 */
export interface AuthApiInterface {
    /**
     * get the current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    getApiAuthMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MercuryEntitiesUser>>;

    /**
     * get the current user
     */
    getApiAuthMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MercuryEntitiesUser>;

    /**
     * login to fetch a new JWT token
     * @param {PostApiAuthLogin} postApiAuthLogin 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    postApiAuthLoginRaw(requestParameters: PostApiAuthLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MercuryEntitiesToken>>;

    /**
     * login to fetch a new JWT token
     */
    postApiAuthLogin(requestParameters: PostApiAuthLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MercuryEntitiesToken>;

}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI implements AuthApiInterface {

    /**
     * get the current user
     */
    async getApiAuthMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MercuryEntitiesUser>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // bearer_auth authentication
        }

        const response = await this.request({
            path: `/api/auth/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MercuryEntitiesUserFromJSON(jsonValue));
    }

    /**
     * get the current user
     */
    async getApiAuthMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MercuryEntitiesUser> {
        const response = await this.getApiAuthMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * login to fetch a new JWT token
     */
    async postApiAuthLoginRaw(requestParameters: PostApiAuthLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MercuryEntitiesToken>> {
        if (requestParameters.postApiAuthLogin === null || requestParameters.postApiAuthLogin === undefined) {
            throw new runtime.RequiredError('postApiAuthLogin','Required parameter requestParameters.postApiAuthLogin was null or undefined when calling postApiAuthLogin.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // bearer_auth authentication
        }

        const response = await this.request({
            path: `/api/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostApiAuthLoginToJSON(requestParameters.postApiAuthLogin),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MercuryEntitiesTokenFromJSON(jsonValue));
    }

    /**
     * login to fetch a new JWT token
     */
    async postApiAuthLogin(requestParameters: PostApiAuthLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MercuryEntitiesToken> {
        const response = await this.postApiAuthLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
